# For some odd reason the docker file did not work. 
# I had to manually go and install the drivers in Docker Desktop(open a shell)

FROM php:fpm

RUN docker-php-ext-install pdo pdo_mysql
RUN docker-php-ext-install mysqli
RUN "echo AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
CMD "echo AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"