version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "8080:8080"
        volumes:
                - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
                - ./www:/www
    php:
      image: php:fpm
      volumes:
        - ./www:/www
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_USER: 'test'
            MYSQL_PASSWORD: 'horriblepassword'
            MYSQL_ROOT_PASSWORD: 'test123'
            MYSQL_DATABASE: 'testDB'
        volumes:
            - mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
volumes:
    mysqldata: {}